---
- hosts: all
  become: true

  tasks:
    - name: Check UFW status
      command: ufw status
      register: ufw_status
      ignore_errors: true  # Ignore errors if UFW is not installed

    - name: Display UFW status
      debug:
        msg: "UFW status: {{ ufw_status.stdout }}"
      when: ufw_status.rc == 0

    - name: Handle case where UFW is not installed or disabled
      debug:
        msg: "UFW is either not installed or disabled."
      when: ufw_status.rc != 0
